on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: addition of two no
    - uses: new/someaction@v1
      with:
          x: 10
          y: 20
          sum : ${{ $x+$y }}
     
      #env:
          #NUM: 5
      #env:
        #x1: 30
        #y2: 40
        
       
          #echo ::set-output name=sum::$(($x+$y))
    - run: echo "sum is  $sum"
