on: push

jobs:
  job1:
    runs-on: ubuntu-latest
   
    outputs:
        value: ${{ steps.random-number-generator.outputs.random-id }}

    steps:
    - id: random-number-generator
      run: echo "::set-output name=random-id::hello"
  job2:
   runs-on: ubuntu-latest
   needs: job1
   steps:
    - run: echo ${{needs.job1.outputs.value}}
 
    

   
      
    
