on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: addition of two no
      uses: einaregilsson/build-number@v3
      with:
          x: '10'
          y: '20'
          sum: ${ x + y }
          INPUT_TOKEN: ''

    - name: print the data
    #- uses: new/someaction@v2
      run: echo "sum is  $sum"
     
      #env:
          #NUM: 5
      #env:
        #x1: 30
        #y2: 40
        
       
          #echo ::set-output name=sum::$(($x+$y))
    
