on: push

jobs:
  build:
    runs-on: ubuntu-latest
   
    outputs:
        value: ${{ steps.random-number-generator.outputs.random-id }}

    steps:
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM) 
